### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by jcelerier** [animatedb/oovaide#1]
Hello,

A quick `git clone; cmake; make` gives : 

```
[ 60%] Building CXX object oovcde/CMakeFiles/oovcde.dir/ClassDiagram.cpp.o
/home/jcelerier/travail/oovcde/source/oovcde/ClassDiagram.cpp: In function ‘const ClassDrawOptions& getDrawOptions()’:
/home/jcelerier/travail/oovcde/source/oovcde/ClassDiagram.cpp:23:53: erreur: ‘OptGuiShowOperReturn’ was not declared in this scope
     dopts.drawOperReturn = gGuiOptions.getValueBool(OptGuiShowOperReturn);
                                                     ^
/home/jcelerier/travail/oovcde/source/oovcde/ClassDiagram.cpp:30:54: erreur: ‘OptGuiShowRelationKey’ was not declared in this scope
     dopts.drawRelationKey = gGuiOptions.getValueBool(OptGuiShowRelationKey);
                                                      ^
```

**Comment by animatedb** [comment]
I don't have time to look at it now, but that symbol is defined in oovCommon/Options.h.  I will look at it more later.

**Comment by animatedb** [comment]
There was an old copy of Options.h and Options.cpp in the oovcde directory.  I have now removed them in the github repository.  For your local copy, just delete these two files in the oovcde directory, or git clone to get the new fix.

**Comment by jcelerier** [comment]
Nice, thank you !
Is there an easy way to work with CMake projects ?

**Comment by animatedb** [comment]
I am not sure if you are talking about analysis or building. The analysis mainly scans the directory tree and analyzes all .h and .cpp files.  It uses pkg-config to help with the compiler arguments, so it should be easy to set up some dependencies under the Analysis/Settings menu, then use the External Project Packages button.  Even if all include directories are not properly set up, much of the analysis can still give useful information.  It sounds like I should think about a way to use some CMake files to use external packages automatically.  

For the building, it attempts to find all dependencies with its own internal builder since it analyzes include and library dependencies.  This should work well for most pure C++ projects.

If you have something else that is required, let me know and I may try to find a way to incorporate it.

**Comment by animatedb** [comment]
I forgot to mention that during analysis and building, the builder finds include files under the root directory tree for the project and automatically adds the directories for the compiler.  Exclude paths can be set to exclude some directories if needed.
