### ISSUE TITLE
Invalid oovCommon/cmake_install.cmake generated

### ISSUE THREAD

**Issue by teZeriusz** [animatedb/oovaide#2]
Mentioned file have extra windows endline chars in wrong place - that prevent make install from success.

**Comment by animatedb** [comment]
I generally have not used CMake and install, but I will attempt to get it working for you.  If your goal is simply to get the program working, it is easy to copy all of the executables (oovBuilder, oovcde, oovCMaker, oovCppParser, and oovEdit) into the bin or bin-linux directory, and it should work ok.  The programs generally just need the glade files, and the libclang run time library.

It looks like the CMakelists.txt must have the set_target_properties so that there are backslashes without spaces on the following lines.  I will start to fix this soon for the supplied files and also the CMake file generator inside of Oovcde.

**Comment by animatedb** [comment]
The CMakeLists.txt files are now fixed for the syntax errors, but the glade files must still be copied to the bin directory.  I will do that next.

**Comment by animatedb** [comment]
All required files are now installed to /usr/local/bin by default on Linux.  All of the Oovcde components were fixed to load processes and glade files from the current directory, /usr/local/bin or /usr/bin.
