### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [animatedb/oovaide#3]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [CMaker::writeFile](https://github.com/animatedb/oovcde/blob/e6db317cc8c898eb020bde7a866234f1ac590598/source/oovCMaker/oovCMaker.cpp#L23)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) ⇒ [loadXmiFile](https://github.com/animatedb/oovcde/blob/793d2da34072eb1b93ada869ab5e7691066f6f67/source/oovcde/Xmi2Object.cpp#L860)

**Comment by animatedb** [comment]
A new error handling interface was added. Error handling for files was added to the following areas:
- XML files
- CMake files
- library symbols
- build configuration files
- component information files
- include dependencies
- packages
- diagrams
- duplicate hash files

There may be a few spots yet that are not covered, but I consider them non-critical since they are for logging of diagnostics or other minor purposes.
