### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by val-antonescu** [animatedb/oovaide#4]
Very nice project. I just run into this by random and I managed to compile it on a Fedora 21. However the fonts in class diagram view for example seem to be very small. Is there a way to resize these fonts?

**Comment by animatedb** [comment]
A font size dialog was added on the right click in any diagram in version 15-11.  It is not perfect since it does not retain the font size when restored from disk, but setting the font size for the restored dialog will display properly.

Another option that is always there is to use Inkscape to edit the SVG output from OovAide.  This is quite a bit more difficult, but does allow for a lot of customization using Inscape's scaling feature.
